### ISSUE TITLE
DB Schema

### ISSUE THREAD

**Issue by sumeetjain** [sumeetjain/vinyl-archive#3]
Use Google Sheets to prepare and get approval for the database schema. Add a few rows of sample data to each table.

Submit using `/submit` as usual to get an instructor to take a look.

**Comment by sumeetjain** [comment]
FYI - ActiveRecord will automatically add an `id` column to every table that's created using a migration script. So just make sure you don't actually add (for example) an `album_id` column to the `albums` table. That would be redundant.

Make sure you define column names as all lowercase, as that's how AR likes them.

Make sure your table names are plural, as that's how AR likes them.

Avoid naming columns the same thing as the model itself. For example, don't name a column in the `albums` table "album". Everything in that table relates to albums, so use a more descriptive label like "title" or something.

For cells that store a URL, use `text` instead of `string`, because it's possible (though, admittedly not likely, that a URL might many hundred characters).

The `images` table should have an additional column to indicate what kind of image it is (e.g. "cover", "insert", etc). Don't name it `type`, as that's a "reserved word" in Rails.

In `song`, change `song_name` to `name` (or `title`). It's already obvious it's the song's name, as it's the `songs` table.

**Comment by halfghaninne** [comment]
Thanks for revising per Sumeet's suggestions.

**Tiny pieces of feedback:**
1. For `artists`, the `from` column might more appropriately be named something like `city`. It's _slightly_ more expressive, considering you might be using it in a context like `<%= @band.city %>`
2. Likewise, for `images`, the `img_url` column can become `url` to avoid redundancy.

Otherwise, 👍  -- No need to resubmit.

**Comment by sumeetjain** [comment]
https://docs.google.com/spreadsheets/d/1frGuNmjuz1k2Yuh8ZevbuSgZqTQgWVWgVGln4xjCOE0/edit?usp=sharing
