### ISSUE TITLE
Set up AWS S3 for file uploads on Staging

### ISSUE THREAD

**Issue by sumeetjain** [sumeetjain/vinyl-archive#51]
This task is for Jerry, when he rotates onto this project.

---
- [x] What is AWS? What is S3?
- [x] Why is S3 needed for file uploads on Staging? (Hint: It's specific to Heroku.)
- [x] How does Carrierwave need to be configured to use S3?
- [ ] Build a sandbox app that uses Carrierwave and S3 _locally_.
- [ ] Build a sandbox app that uses Carrierwave and S3 on a Heroku app.
  - You'll need to make your own Heroku application, which is not hard: From the project's directory (which must be a Git repo), run `heroku create`. Then run `heroku addons:create heroku-postgresql:hobby-dev` (to create an empty database on Heroku for your application to use). Then `git push heroku master` to deploy.
  - You can use the sandbox app that you used to get Carrierwave and S3 working locally, if you don't want to make a new application.

Ask questions as you arrive at them! Even the conceptual ones can be `/ask`ed in Slack.

Once you have the above completed...
- [ ] Implement S3 on Staging for this project.

**Comment by DiwthL83** [comment]
1. AWS is a cloud web service provided by Amazon. S3 is Amazon's Simple Storage Service, a service that allows scalable storage solutions for various types of media and data.
2. S3 is needed for Heroku apps because their platform does not provide a storage solution for media. Heroku is a development platform.
3. Carrierwave needs to have an uploader installed (https://github.com/carrierwaveuploader/carrierwave#getting-started), and must then be configured to point to S3 as the storage directory (https://github.com/carrierwaveuploader/carrierwave#changing-the-storage-directory).

Not sure I'm following on the last two before implementing. Are you asking for me to build one app on my machine, and one on Heroku's platform? What is the benefit to doing so?

**Comment by sumeetjain** [comment]
The idea with _Build a sandbox app that uses Carrierwave and S3 locally._ is to build a _new_ Rails application where you can try out Carrierwave and uploading to S3. This is to prevent you from needing to make many changes to the Vinyl Archive application without having a better idea of what to do.

It's a good practice in general to use sandbox apps to try a new tool/technique, since they're meant to be temporary. They're practice apps.

The idea with _Build a sandbox app that uses Carrierwave and S3 on a Heroku app._ is to deploy the sandbox app that you'd built. That way, you can also see how setting up S3 on Heroku would work.

Once you have that done, coming back to the Vinyl Archive project and implementing S3 for uploads should be easy.

This isn't a change of effort–it's just a _movement_ of effort. We're moving the effort needed to learn S3 from within the VA application to instead be contained within a sandbox app.

**Comment by sumeetjain** [comment]
(Please feel free to ask follow up questions or stop by!)
